CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS country VARCHAR(16) NOT NULL DEFAULT 'SG',
    ADD COLUMN IF NOT EXISTS currency VARCHAR(16) NOT NULL DEFAULT 'SGD',
    ADD COLUMN IF NOT EXISTS locale VARCHAR(32) NOT NULL DEFAULT 'en-SG',
    ADD COLUMN IF NOT EXISTS platform VARCHAR(32) NOT NULL DEFAULT 'shopify';

ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS platform VARCHAR(64) NOT NULL DEFAULT 'shopify',
    ADD COLUMN IF NOT EXISTS supported_countries VARCHAR(255) NOT NULL DEFAULT 'SEA,SG',
    ADD COLUMN IF NOT EXISTS warehouse_region VARCHAR(16) NOT NULL DEFAULT 'SG',
    ADD COLUMN IF NOT EXISTS delivery_days INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS cross_border_eligible BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS recommendation_tags VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS embedding vector(8);

ALTER TABLE IF EXISTS orders
    ADD COLUMN IF NOT EXISTS country VARCHAR(16) NOT NULL DEFAULT 'SG',
    ADD COLUMN IF NOT EXISTS warehouse_region VARCHAR(16) NOT NULL DEFAULT 'SG',
    ADD COLUMN IF NOT EXISTS product_ids_text VARCHAR(1000) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(32) NOT NULL DEFAULT 'paid',
    ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(40) NOT NULL DEFAULT 'ready_to_ship',
    ADD COLUMN IF NOT EXISTS promised_delivery_days INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS risk_level VARCHAR(16) NOT NULL DEFAULT 'low';